services:
  - type: web
    name: formulario
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    rootDir: .
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
